# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-28 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subategory',
            new_name='Subcategory',
        ),
    ]
